In [8]:
# basic functions
import math
import numpy as np

In [9]:
#visual style
import matplotlib.pyplot as plt

%matplotlib inline

In [10]:
from scipy.stats import norm
from scipy.stats import beta

In [19]:
# see page 135 for this in R
# [lower bound, upper bound] are in parens
beta.ppf([0.025,0.975], 300,39700) # need to understand this function

array([0.00667807, 0.00836856])

In [11]:
# how many shots will the shooter make?
# who should i bet on in horse?

rk = beta.ppf([0.1,0.9],2,4)
rk[1] - rk[0]

0.47165541607367045

In [12]:
ph = beta.ppf([0.1,0.9],4,2)
ph[1] - ph[0]

0.4716554160736704

## `Excercises`

*1. Using the code example for plotting the PDF on page 127, plot the CDF and quantile functions.*

In [13]:
subscribed = 300
visited = 40000 - subscribed

lower_bound = 0.025
upper_bound = 0.975

In [15]:
quantiles = beta.ppf([lower_bound,upper_bound],a=subscribed, b=visited)
quantiles

array([0.00667807, 0.00836856])

*2. Returning to the task of measuring snowfall from Chapter 10, say you have the following measurements (in inches) of snowfall:*

*7.8, 9.4, 10.0, 7.9, 9.4, 7.0, 7.0, 7.1, 8.9, 7.4*

*What is the 99.9 confidence interval for the true value of snowfall?*

In [42]:
measurements = [7.8, 9.4, 10.0, 7.9, 9.4, 7.0, 7.0, 7.1, 8.9, 7.4]

snow_mean = np.mean(measurements)
snow_std = np.std(measurements)

lower_bound = 0.0005
upper_bound = 1-lower_bound

In [43]:
snowfall = norm.ppf([lower_bound,upper_bound], 
                    loc=snow_mean,
                    scale=snow_std,
                   )

snowfall

array([ 4.647675, 11.732325])

In [38]:
# answer in book 4.46, 11.92...is it norm vs qnorm?