In [1]:
# basic functions
import math
import numpy as np

In [2]:
#visual style
import matplotlib.pyplot as plt

%matplotlib inline

In [3]:
from scipy.stats import norm
from scipy.stats import beta

In [4]:
# see page 135 for this in R
# [lower bound, upper bound] are in parens
beta.ppf([0.025,0.975], 300,39700) # need to understand this function

array([0.00667807, 0.00836856])

In [5]:
# how many shots will the shooter make?
# who should i bet on in horse?

rk = beta.ppf([0.1,0.9],2,4)
rk[1] - rk[0]

0.47165541607367045

In [6]:
ph = beta.ppf([0.1,0.9],4,2)
ph[1] - ph[0]

0.4716554160736704

## `Excercises`

*1. Using the code example for plotting the PDF on page 127, plot the CDF and quantile functions.*

In [7]:
subscribed = 300
visited = 40000 - subscribed

lower_bound = 0.025
upper_bound = 0.975

In [8]:
quantiles = beta.ppf([lower_bound,upper_bound],a=subscribed, b=visited)
quantiles

array([0.00667807, 0.00836856])

*2. Returning to the task of measuring snowfall from Chapter 10, say you have the following measurements (in inches) of snowfall:*

*7.8, 9.4, 10.0, 7.9, 9.4, 7.0, 7.0, 7.1, 8.9, 7.4*

*What is the 99.9 confidence interval for the true value of snowfall?*

In [9]:
measurements = [7.8, 9.4, 10.0, 7.9, 9.4, 7.0, 7.0, 7.1, 8.9, 7.4]

snow_mean = np.mean(measurements)
snow_std = np.std(measurements)

lower_bound = 0.0005
upper_bound = 1-lower_bound

In [10]:
snowfall = norm.ppf([lower_bound,upper_bound], 
                    loc=snow_mean,
                    scale=snow_std,
                   )

snowfall

array([ 4.647675, 11.732325])

In [38]:
# answer in book 4.46, 11.92...is it norm vs qnorm?

*3. A child is going door to door selling candy bars. So far she has visited 30 houses and sold 10 candy bars. She will visit 40 more houses today. What is the 95 percent confidence interval for how many candy bars she will sell for the rest of the day?*

In [29]:
sell_percent = beta.ppf([0.025,0.975],10,20)
sell_percent

array([0.17938365, 0.50832335])

In [30]:
sell_percent[0] * 40, sell_percent[1] * 40

(7.175345969404473, 20.332934152399602)

In [31]:
beta.ppf([0.025,0.975],45,5)

array([0.80398582, 0.9660283 ])

In [32]:
from scipy.stats import binom

In [35]:
binom.cdf(0.975,10,0.18)

0.1374480313359607

In [36]:
binom.cdf(0.975,10,.51)

0.0007979226629761198

In [38]:
binom.ppf([0.025,0.975],10,0.5)

array([2., 8.])

In [41]:
binom.stats(30,0.33,moments='mv')

(array(9.9), array(6.633))

In [42]:
binom.pmf(7,30,0.18)

0.12982587268143608

In [43]:
binom.pmf(20,30,0.67)

0.1529001382047916

In [44]:
binom.pmf(10,30,0.5)

0.027981600724160505