In [1]:
# basic functions
import math
import numpy as np

In [2]:
#visual style
import matplotlib.pyplot as plt

%matplotlib inline

In [3]:
from scipy.stats import norm

In [4]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

In [5]:
np.quantile(data,[0.05,0.90])

array([1.45, 9.1 ])

In [10]:
from scipy.stats import beta
from scipy.stats import mstats

In [ ]:
mstats.quantile()

In [7]:
m = np.mean(data)
std = np.std(data)

In [15]:
norm.ppf([0.05,0.95],loc=2,scale=9)

array([-12.80368264,  16.80368264])

In [13]:
beta.cdf([0.05,0.95],300,39700)

array([1., 1.])

In [19]:
# see page 135 for this in R
# [lower bound, upper bound] are in parens
beta.ppf([0.025,0.975], 300,39700) # need to understand this function

array([0.00667807, 0.00836856])

In [45]:
subscribers = 300
visits = 40000 - subscribers

hi = beta.cdf([0.0085,1],a=subscribers,b=visits)
yy = hi[-1] - hi[0]

In [30]:
hi = beta.cdf([0.0,0.0065],300,39700)
zz = hi[-1] - hi[0]

In [50]:
round(yy,3)/round(zz,3)

1.5

In [60]:
# how many buckets will shooter make?
# who should i bet on in horse?

rk = beta.ppf([0.1,0.9],2,4)
rk[1] - rk[0]

0.47165541607367045

In [61]:
ph = beta.ppf([0.1,0.9],4,2)
ph[1] - ph[0]

0.4716554160736704